#!/usr/bin/env cargo-update
[package]
name = "notify-server"
version = "0.0.0"
authors = ["Matthias Fauconneau <matthias.fauconneau@gmail.com>"]
edition = "2018"

[dependencies]
env_logger = ""
notify-rust = ""
iced = { path = "iced" } #{ git = "https://github.com/hecrj/iced.git" }
